#%RAML 1.0 Library

types:
  address:
    properties:
      type:  
        type: string
        required: false
        default: home
        enum:
        - home
        - condo
        - apartment
      number:  
        type: number
        required: true
      street:  
        type: string
        required: true
      Unit:  
        type: string
        required: false
      City:  
        type: string
        required: true
      State:  
        type: string
        required: true
      zipcode:  
        type: string
        required: true