#%RAML 1.0 DataType

uses:
  add: address.raml
  comm: communication.raml
  iden: identification.raml
type: object
properties:
  Identification:  
    type: iden.id
    required: true
  Address:  
    type: add.address[]
    required: true
  Communication:  
    type: comm.comm[]
    required: true